[package]
name = "guess_num"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.3.14"
#"0.3.14"是"^0.3.14"的缩写版本，意思是允许任何>=0.3.14&&<0.4.0的版本
#首次构建时，Cargo 会解析出符合该约束的最新版本（例如 0.3.30）
#并将其版本号锁定在 Cargo.lock 中
#因此锁定的版本不一定是 0.3.14，而是当时可用的最新兼容版本
#如果后续依赖包发布了新补丁（如 0.3.31）
#由于 lock 文件的存在，构建时仍会继续使用已锁定的旧版本（例如 0.3.30）
#如果要更新包，执行cargo update
#cargo update 会在满足当前 Cargo.toml 中版本约束的前提下，将依赖更新到允许的最新版本
#如果要更改版本约束，直接修改toml文件即可，如把0.3.x改到0.4.x

#toml文件里的注释要用#而不是//
